### ISSUE TITLE
activecollab.com - project management product/service

### ISSUE THREAD

**Issue by isvsecwatch-report** [isvsecwatch/httpstracker#69]
**SSL Server Test Results**
https://www.ssllabs.com/ssltest/analyze.html?d=activecollab.com (B)

**Comment by MattCotterellNZ** [comment]
This appears to be resolved: 
https://www.ssllabs.com/ssltest/analyze.html?d=activecollab.com (A+)

**Comment by isvsecwatch-report** [comment]
Looks like it! There's an extra cert in the chain, but that's minor. Closing ticket.
