### ISSUE TITLE
my.vmware.com - customer login

### ISSUE THREAD

**Issue by isvsecwatch-report** [isvsecwatch/httpstracker#94]
**SSL Server Test Results**
https://www.ssllabs.com/ssltest/analyze.html?d=my.vmware.com (B)

**Cipherscan Results**

```
Target: my.vmware.com:443

prio  ciphersuite        protocols              pfs_keysize
1     AES256-GCM-SHA384  TLSv1.2
2     AES256-SHA256      TLSv1.2
3     AES128-GCM-SHA256  TLSv1.2
4     AES128-SHA256      TLSv1.2
5     AES256-SHA         TLSv1,TLSv1.1,TLSv1.2
6     AES128-SHA         TLSv1,TLSv1.1,TLSv1.2
7     DES-CBC3-SHA       TLSv1,TLSv1.1,TLSv1.2
8     RC4-SHA            TLSv1,TLSv1.1,TLSv1.2

Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: 7200
OCSP stapling: not supported
Server side cipher ordering
```

**Cipherscan Analysis**

```
my.vmware.com:443 has bad ssl/tls

Things that are bad:
* remove cipher RC4-SHA

Changes needed to match the intermediate level:
* remove cipher RC4-SHA
* consider enabling OCSP Stapling

Changes needed to match the modern level:
* remove cipher AES256-GCM-SHA384
* remove cipher AES256-SHA256
* remove cipher AES128-GCM-SHA256
* remove cipher AES128-SHA256
* remove cipher AES256-SHA
* remove cipher AES128-SHA
* remove cipher DES-CBC3-SHA
* remove cipher RC4-SHA
* disable TLSv1
* consider enabling OCSP Stapling
```

**Comment by yuhong** [comment]
Note the Baltimore->GTE CyberTrust intermediate is similar in purpose to the GeoTrust->Equifax intermediate, and notice that SSL Labs clearly shows the two cert chains.

**Comment by isvsecwatch-report** [comment]
It's not an intermediate, in this case, but the root certificate. It is flagged because it gets sent by the server while being present in the trust store. Removing it from the chain sent by the server would resolve the issue. One chain, not two, which should not contain the root certificate.

If all you're going to contribute are confusing or incorrect comments, please refrain from doing so altogether.

**Comment by yuhong** [comment]
In this case, it is not the root certificate that is being sent.

**Comment by yuhong** [comment]
In this case, it is not the root. Pay attention to "Additional Certificates (if supplied)", particularly the issuer.

**Comment by isvsecwatch-report** [comment]
If certificates are in the list, they are being supplied by the server. The SSL Server Test results clearly state that _three_ (3) certificates are supplied (leaf, intermediate, and root) and marks 'extra certs' as an issue _because_ it sends the root certificate when it is not needed.

As said, please refrain from commenting if all you're doing is posting incorrect or confusing comments. If you are unable to we will restrict your ability to contribute to this repository.

**Comment by yuhong** [comment]
Notice it says "In trust store" for the root. If the server was sending the root, it would also say "sent by server".

**Comment by isvsecwatch-report** [comment]
That is under a different header, 'Certification Paths', _not_ 'Additional Certificates (if supplied)'. It details the verification chain the SSL Server Test client follows.

Last warning.

**Comment by yuhong** [comment]
I know.

**Comment by isvsecwatch-report** [comment]
Updated, currently at A- due to lack of secure server-side renegotiation.

**Cipherscan Results**

```
Target: my.vmware.com:443

prio  ciphersuite                  protocols              pfs                 curves
1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits  prime256v1
2     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1
3     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits  prime256v1
4     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
5     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits  prime256v1
6     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
7     AES256-GCM-SHA384            TLSv1.2                None                None
8     AES128-GCM-SHA256            TLSv1.2                None                None
9     AES256-SHA256                TLSv1.2                None                None
10    AES128-SHA256                TLSv1.2                None                None
11    AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None

Certificate: trusted, 2048 bits, sha256WithRSAEncryption signature
TLS ticket lifetime hint: 7200
OCSP stapling: not supported
Cipher ordering: server
Curves ordering: server - fallback: no
Server DOESN'T support secure renegotiation
Server supported compression methods: NONE
TLS Tolerance: yes
```

Other issues fixed, good enough.
