### ISSUE TITLE
HomeBank ( http://homebank.free.fr/ ) - Free personal finance software

### ISSUE THREAD

**Issue by tdelmas** [isvsecwatch/httpstracker#97]
No https at all.

https://bugs.launchpad.net/homebank/+bug/1490346

**Comment by isvsecwatch-report** [comment]
This is hosted on a free subdomain at a French ISP, not even on its own domain, and secure protocols are not supported. If the original author currently refuses to accept it as a problem, there's not much we can do from here either.

Closing as unresolved.
